########################################################################
# Makefile for MPItutorial
#
########################################################################

CC         =  mpicc
CCFLAGS    =  -O3
LIBS       =  -lmpi

all:
	@echo "Usage: make hello"

ass1:          ass1.c
	$(CC) $(CCFLAGS) -o ass1 ass1.c $(LIBS)
